POST https://{{host}}/dwc/LINKEDDWC1/sap/bc/ina/service/v2/GetResponse?= HTTP/1.1
X-Csrf-Token: Fetch
X-Sap-Boc-Approuter-Orca-Context: {{X-Sap-Boc-Approuter-Orca-Context}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-Sap-Boc-User-Properties: {{X-Sap-Boc-User-Properties}}
Connection: keep-alive
Content-Length: 5788

{
  "Metadata": {
    "Capabilities": [
      "AggregationNOPNULL",
      "AggregationNOPNULLZERO",
      "AsyncBatchRequest",
      "AsyncMetadataBatchRequest",
      "AttributeHierarchy",
      "AttributeHierarchyHierarchyFields",
      "AttributeHierarchyUniqueFields",
      "AttributeValueLookup",
      "AverageCountIgnoreNullZero",
      "BugFixHierarchyFlatKeys",
      "CEScenarioParams",
      "CalculateWithNullCellsUnitType",
      "CalculatedDimension",
      "CancelRunningRequests",
      "CellValueOperand",
      "ClientCapabilities",
      "Conditions",
      "CubeBlending",
      "CubeBlendingCustomMembers",
      "CubeBlendingMemberSorting",
      "CubeBlendingOutOfContext",
      "CubeBlendingProperties",
      "CubeBlendingReadMode",
      "CurrencyTranslation",
      "CurrentMemberFilterExtension",
      "CustomDimension1MemberType",
      "CustomDimension2",
      "CustomDimensionFilterCapabilities",
      "CustomDimensionMemberExecutionStep",
      "CustomMemberSortOrder",
      "DataEntryOnUnbooked",
      "DatasourceAtService",
      "DimensionDescription",
      "DimensionKindChartOfAccounts",
      "DimensionKindEPMVersion",
      "EPMResponseListSharedVersions",
      "ExceptionAggregationAverageNullInSelectionMember",
      "ExceptionAggregationCountNullInSelectionMember",
      "ExceptionAggregationDimsAndFormulas",
      "ExceptionAggregationFirstLastInSelectionMember",
      "ExceptionSettings",
      "Exceptions",
      "ExpandHierarchyBottomUp",
      "ExtHierarchy",
      "ExtendedDimensions",
      "ExtendedDimensionsChangeDefaultRenamingAndDescription",
      "ExtendedDimensionsCopyAllHierarchies",
      "ExtendedDimensionsFieldMapping",
      "ExtendedDimensionsJoinCardinality",
      "ExtendedDimensionsJoinColumns",
      "ExtendedDimensionsOuterJoin",
      "ExtendedDimensionsSkip",
      "FastPath",
      "FixMetaDataHierarchyAttributes",
      "FlatKeyOnHierarchicalDisplay",
      "HierarchyAttributePathPresentationType",
      "HierarchyDataAndExcludingFilters",
      "HierarchyKeyTextName",
      "HierarchyNavigationDeltaMode",
      "HierarchyPath",
      "HierarchyPathUniqueName",
      "HierarchyTrapezoidFilter",
      "HierarchyVirtualRootNode",
      "IgnoreUnitOfNullValueInAggregation",
      "IgnoreUnitOfZeroValueInAggregation",
      "InputEnablementFilterSettings",
      "InputReadinessStates",
      "InputReadinessWithNavigationalAttributes",
      "IsVirtualDescription",
      "IteratedFormula",
      "ListReporting",
      "LocaleSorting",
      "MasterReadModeByDimensionGrouping",
      "MaxResultRecords",
      "MdsExpression",
      "MeasureMemberCurrencyTranslations",
      "MeasureMemberDetails",
      "MeasureMemberMetadata",
      "MetadataCubeQuery",
      "MetadataDataCategory",
      "MetadataDataSourceDefinitionValidation",
      "MetadataDataSourceDefinitionValidationExposeDataSource",
      "MetadataDefaultResultStructureResultAlignmentBottom",
      "MetadataDimensionCanBeAggregated",
      "MetadataDimensionDefaultMember",
      "MetadataDimensionGroup",
      "MetadataDimensionVisibility",
      "MetadataDynamicVariable",
      "MetadataExtendedDimensionVisibility",
      "MetadataHierarchyLevels",
      "MetadataHierarchyRestNode",
      "MetadataHierarchyStructure",
      "MetadataHierarchyUniqueName",
      "MetadataIsDisplayAttribute",
      "MetadataRepositorySuffix",
      "MetadataSemanticType",
      "MultipleExAggDimsInCalcPlan",
      "NullZeroSuppression",
      "Obtainability",
      "PagingTupleCountTotal",
      "PerformanceAnalysis",
      "PersistResultSet",
      "PlanningOnCalculatedDimension",
      "ReadMode",
      "ReadModeRelatedBooked",
      "RemoteBlending",
      "RemoteBlendingBW",
      "RemoteBlendingMetadata",
      "RemoteFilter",
      "RequestTimeZone",
      "RestrictedMembersConvertToFlatSelection",
      "ResultSetAxisType",
      "ResultSetCellDataType",
      "ResultSetCellExplain",
      "ResultSetCellFormatString",
      "ResultSetCellNumericShift",
      "ResultSetInterval",
      "ResultSetState",
      "ResultSetUnitIndex",
      "ReturnErrorForInvalidQueryModel",
      "ReturnRestrictedAndCalculatedMembersInReadmodeBooked",
      "ReturnedDataSelection",
      "RootOrphanNodesAfterVisibilityFilter",
      "SP9",
      "SemanticalErrorType",
      "SetNullCellsUnitType",
      "SetOperandCurrentMemberSingleNavigation",
      "SortNewValues",
      "SpatialClustering",
      "SpatialFilterSRID",
      "StatisticalAggregations",
      "SupportsComplexFilters",
      "SupportsCubeBlendingAggregation",
      "SupportsDataCellMixedValues",
      "SupportsEncodedResultSet",
      "SupportsEncodedResultSet2",
      "SupportsExtendedSort",
      "SupportsHierarchySelectionAsFlatSelection",
      "SupportsIgnoreExternalDimensions",
      "SupportsInAModelMetadata",
      "SupportsMemberVisibility",
      "SupportsSetOperand",
      "SupportsSpatialFilter",
      "SupportsSpatialTransformations",
      "TechnicalAxis",
      "Totals",
      "TotalsAfterVisibilityFilter",
      "UndefinedTupleCountTotals",
      "UniqueAttributeNames",
      "UnivModelInheritedPropsRaisedPriority",
      "UniversalModel",
      "UseEPMVersion",
      "ValuesRounded",
      "Variables",
      "VirtualDataSourceVariableValues",
      "VisibilityFilter",
      "VisualAggregation"
    ],
    "Context": "ListReporting",
    "DataSource": {
      "Context": "{\"sessionContext\":{}}",
      "InstanceId": "90f35fe0-08a6-ad00-9760-8709c4469389",
      "ObjectName": "\/sap.epm.C6CYXYCBNK8C00000000000000\/C6CYXYCBNK8C00000000000000_qs",
      "SchemaName": "TEST_SPACE#SAC_42VBP1YQ07B7ZQ5X",
      "Type": "Planning"
    },
    "Expand": [
      "Cube"
    ],
    "Language": "EN"
  },
  "Options": [
    
  ]
}