
POST https://{{host}}/cloud/query HTTP/1.1
Username: {{username}}
Password: {{password}}
Tenanturl: {{tenanturl}}
Appname: ppro-firefly-{{suffix}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Content-Length: 411

{
    "inaSystemURI": null,
    "cubeReference": {
        "schema": "TENANT_3",
        "epmModel": "/t.3.C10TY063N9V8H0P299XL43CMIO/C10TY063N9V8H0P299XL43CMIO_qs"
    },
    "outputSetting": {
        "inaQuery": false
    },
	  "attributes": [{"name":"Date.DATE"}, {"name":"Entity"}],
	  "dimensions": [],
	  "accounts": [{"name": "H111100"}],
	  "versions": ["public.Actual", "private.3_NADIR.MyForecast"]
}